version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: StudyDB
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: StudyDB
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
      build: 
        context: .
        dockerfile: .devcontainer/Dockerfile 
      container_name: StudyApp
      volumes:
        - ..:/workspaces:cached
      ports:
        - "8080:8080"
        - "5005:5005"
      depends_on:
        - db
      command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  db-data: